_commit: adada77
_src_path: gh:monarch-initiative/koza-ingest-template
copyright_year: '2026'
email: info@monarchinitiative.org
full_name: Monarch Initiative
github_handle: monarch-initiative
github_org: monarch-initiative
license: BSD-3-Clause
project_description: CTD chemical to disease association ingest
project_name: ctd-ingest
project_slug: ctd_ingest
